// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';

var Curry = require("bs-platform/lib/js/curry.js");
var React = require("react");
var Vrroom = require("../src/Vrroom.bs.js");

var maybeErrorClass = "is-oops";

function ClassNames(Props) {
  var className = Curry._1(Vrroom.Helpers.ClassName.join, {
        hd: "tooltip",
        tl: {
          hd: Curry._2(Vrroom.Helpers.ClassName.if_, true, "s-hovered"),
          tl: {
            hd: Curry._1(Vrroom.Helpers.ClassName.fromOption, maybeErrorClass),
            tl: /* [] */0
          }
        }
      });
  return React.createElement("div", undefined, React.createElement("div", {
                  className: className
                }, Vrroom.text("Hello world!")), React.createElement("div", {
                  className: Curry._1(Vrroom.Helpers.ClassName.join, {
                        hd: "tooltip",
                        tl: {
                          hd: Curry._2(Vrroom.Helpers.ClassName.if_, true, "s-hovered"),
                          tl: /* [] */0
                        }
                      })
                }, Vrroom.text("Hello world!")));
}

var isHovered = true;

var make = ClassNames;

exports.maybeErrorClass = maybeErrorClass;
exports.isHovered = isHovered;
exports.make = make;
/* react Not a pure module */
