// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';

var React = require("react");
var Vrroom = require("../src/Vrroom.bs.js");

function ControlIf(Props) {
  return React.createElement("div", undefined, "Hello", React.createElement(Vrroom.Control.If.make, {
                  cond: true,
                  children: Vrroom.text("Hello")
                }));
}

var showHello = true;

var make = ControlIf;

exports.showHello = showHello;
exports.make = make;
/* react Not a pure module */
