// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';

var React = require("react");
var Vrroom = require("../src/Vrroom.bs.js");

var maybeError = "oops!";

function ControlIfSome(Props) {
  return React.createElement("div", undefined, maybeError !== undefined ? maybeError : null, React.createElement(Vrroom.Control.IfSome.make, {
                  option: maybeError,
                  children: Vrroom.text
                }));
}

var make = ControlIfSome;

exports.maybeError = maybeError;
exports.make = make;
/* react Not a pure module */
