// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';

var React = require("react");
var Vrroom = require("../src/Vrroom.bs.js");

function VroomHelpers$ThreeItems(Props) {
  return React.createElement(React.Fragment, {
              children: null
            }, React.createElement("li", undefined, Vrroom.Helpers.text("Item 1")), React.createElement("li", undefined, Vrroom.Helpers.text("Item 2")), React.createElement("li", undefined, Vrroom.Helpers.text("Item 3")));
}

var ThreeItems = {
  make: VroomHelpers$ThreeItems
};

function VroomHelpers(Props) {
  return React.createElement("ol", undefined, React.createElement("li", undefined, Vrroom.Helpers.text("Item 0")), React.createElement(VroomHelpers$ThreeItems, {}), React.createElement("li", undefined, Vrroom.Helpers.text("Item 4")));
}

var make = VroomHelpers;

exports.ThreeItems = ThreeItems;
exports.make = make;
/* react Not a pure module */
